### ISSUE TITLE
show label for label categories of discrete variables

### ISSUE THREAD

**Issue by heike** [yaweige/ggpcp#1]
might need another geom for that - maybe geom_label_pcp. Linking it to the stat_box_pcp should give access to the right data

**Comment by yaweige** [comment]
That's interesting. Current scales branch can generate correct labels. And I still prefer a way to change the default behaviour in how ggplot2 generates panel_params. : ) haha

**Comment by heike** [comment]
solved with geom_pcp_label and geom_pcp_text
